name: Action

on:
  push:
    branches:
      - main  # Set a branch to deploy
  workflow_dispatch:

env:
  INDIR: input
  OUTDIR: content

jobs:
  pandoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: prepare output directories
        run: |
          mkdir -p content
      - name: convert md
        run: |
          make
